name: 'lucky-marty-docker'
services:
  sql:
    container_name: sql
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adonis

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=sql
      - PMA_USER=root
      - PMA_PASSWORD=root

  react:
    container_name: vite
    build:
      context: ./vite
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - adonis

  adonis:
    container_name: adonis
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 3333:3333
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=rJqiE9atRMmF1ba9KPk-podZkD2n5Mw0
      - NODE_ENV=development
      - DB_CONNECTION=mysql
      - DB_HOST=sql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=adonis
      - DB_PORT=3306
    command: sh -c "node build/bin/server.js; tail -f /dev/null"